description = "Ubuntu 24.04 Noble Numbat full image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.19.6"

[stack]
  build-image = "docker.io/paketobuildpacks/build-noble-full:0.0.1"
  id = "io.buildpacks.stacks.noble"
  run-image = "index.docker.io/paketobuildpacks/run-noble-full:latest"
  run-image-mirrors = []
